my-shop/models/__init__.py
from .database import db
from .product import Product


__all__ = [
    "db",
    "Product",
]

my-shop/models/database.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

__all__ = [
    "db",
]

my-shop/models/product.py
from sqlalchemy import Column, Integer, String, Boolean

from .database import db


class Product(db.Model):
    __tablename__ = "products"

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    is_new = Column(Boolean, nullable=False, default=False)
    deleted = Column(Boolean, nullable=False, default=False, server_default='false')

my-shop/app.py
from flask import Flask, request, render_template
from flask_migrate import Migrate

import config
from views import product_app
from models import db

app = Flask(__name__)
app.config.update(
    SERVER_NAME="localhost:5000",
    SQLALCHEMY_DATABASE_URI=config.SQLALCHEMY_DATABASE_URI,
)
app.register_blueprint(product_app, url_prefix="/products")

db.init_app(app)
migrate = Migrate(app, db)


@app.route("/", methods=["GET", "POST"])
def index():
    name = "World"
    if request.method == "POST":
        name = request.form.get('name', 'World')
    return render_template("index.html", name=name)


@app.route("/hello/")
@app.route("/hello/<string:name>/")
def hello(name=None):
    if name is None:
        name = "World"
    return f"<h1>Hello {name}!</h1>"


@app.route('/post/<int:post_id>/')
def show_post(post_id):
    # show the post with the given id, the id is an integer
    return 'Post int %d' % post_id

my-shop/main.py
from app import app

app.config.update(
    DEBUG=True,
)


if __name__ == "__main__":
    app.run(
        host="0.0.0.0",
        debug=True,
    )

my-shop/my_shop/__init__.py
__version__ = '0.1.0'

my-shop/views/__init__.py
from .product import product_app

my-shop/views/product.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for
from werkzeug.exceptions import BadRequest

from models import db, Product


product_app = Blueprint("product_app", __name__)


@product_app.route("/")
def product_list():
    products = Product.query.filter_by(deleted=False).order_by(Product.id).all()
    return render_template("products/index.html", products=products)


@product_app.route("/<int:product_id>/", methods=['GET', 'DELETE'])
def product_detail(product_id: int):
    product = Product.query.filter_by(id=product_id).one_or_none()
    if product is None:
        raise BadRequest(f"Invalid product id #{product_id}")

    if request.method == 'DELETE':
        product.deleted = True
        db.session.commit()
        return jsonify(ok=True)

    return render_template("products/detail.html", product=product)


@product_app.route("/add/", methods=["GET", "POST"], endpoint="product_add")
def add_product():
    if request.method == "GET":
        return render_template("products/add.html")

    data = request.form
    product_name = data.get("product-name")
    if not product_name:
        raise BadRequest("product name is required")
    is_new = bool(data.get("is-new"))
    product = Product(name=product_name, is_new=is_new, deleted=False)
    db.session.add(product)
    db.session.commit()
    return redirect(url_for("product_app.product_list"))

my-shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {#  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/css/bootstrap.min.css"#}
  {#        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">#}

  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

  <title>
    {% block title %}
      Base title
    {% endblock %}
  </title>
</head>
<body>
<div class="container">

<nav class="mb-2 navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{{ url_for('index') }}">MySite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('product_app.product_list') }}">Products</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Cart</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Action
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item disabled" href="#">Personal area</a>
          <a class="dropdown-item disabled" href="#">Support</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Logout</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

  {% block body %}
    Base page
  {% endblock %}
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>

<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

{% block after_body %}
{% endblock %}
<br>
</body>
</html>

my-shop/templates/index.html
{% extends 'base.html' %}

{% block title %}
  Hello
{% endblock %}

{% block body %}
  <h1>Hello {{ name }}!</h1>
{% endblock %}

my-shop/templates/products/add.html
{% extends 'base.html' %}

{% block title -%}
  Add Product
{%- endblock %}

{% block body %}
  <form method="post">
    <div class="form-group">
      <label for="input-product-name">Product name</label>
      <input name="product-name" type="text" class="form-control" id="input-product-name" required>
    </div>
    <div class="form-group form-check">
      <input name="is-new" type="checkbox" class="form-check-input" id="check-is-new">
      <label class="form-check-label" for="check-is-new">New?</label>
    </div>
    <button type="submit" class="btn btn-primary">Add product</button>
  </form>
{% endblock %}

my-shop/templates/products/detail.html
{% extends 'base.html' %}

{% block title -%}
  Product #{{ product.id }}
{%- endblock %}

{% block body %}
  <h1>Product <code id="product-name">{{ product.name }}</code>

    {% if product.is_new %}
      <span class="badge badge-secondary">New</span>
    {% endif %}
  </h1>
  <hr>
  <a href="{{ url_for('product_app.product_list') }}">Product list</a>

  <hr>
  {#  Admin area #}
  <div>
    <button id="delete-product" class="btn btn-danger btn-lg">Delete</button>
  </div>
{% endblock %}

{% block after_body %}
  <script>
    $(function () {
      const name = $('#product-name')
      console.log(name.text())

      $('#delete-product').click(function () {
        $.ajax({
          method: 'DELETE',
          success: function (res) {
            console.log(res)
            console.log(res.data)
          },
          error: function (err) {
            console.error(err)
          },
          complete: function () {
            window.location = '{{ url_for('product_app.product_list') }}'
          },
        })
      })
    });
  </script>
{% endblock %}

my-shop/templates/products/index.html
{% extends 'base.html' %}

{% block title -%}
  Products
{%- endblock %}

{% block body %}
  <h1>Products list</h1>
  <div class="alert alert-info" role="alert">
    Sale only today!
  </div>
  <div class="row">
    <div class="col col-12 col-md-8 col-lg-6 col-xl-4">
      <ul class="list-group">
        {% for product in products %}
          <li class="list-group-item product-item">
            <a class="my-2" href="{{ url_for('product_app.product_detail', product_id=product.id) }}">
              {{ product.name -}}
            </a>
            {% if product.is_new %}
              <span class="badge badge-secondary">New</span>
            {% endif %}
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <a href="{{ url_for('product_app.product_add') }}">Add new product</a>
  <br>
  <small>&copy; OTUS 2020</small>
{% endblock %}

{% block after_body %}
  <script>
    $(function () {
      const productItems = $('.product-item')
      console.log(productItems)
    });
  </script>
{% endblock %}